// <auto-generated />
namespace Hotels.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class First_migrationss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(First_migrationss));
        
        string IMigrationMetadata.Id
        {
            get { return "201712150927539_First_migrationss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
