// <auto-generated />
namespace Hotels.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PassengerBooking_Suit_Migration_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PassengerBooking_Suit_Migration_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121101480_Passenger-Booking_Suit_Migration_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
