// <auto-generated />
namespace Hotels.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_DaysStays_To_Int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_DaysStays_To_Int));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131750308_Change_DaysStays_To_Int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
