// <auto-generated />
namespace Hotels.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_Again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_Again));
        
        string IMigrationMetadata.Id
        {
            get { return "201712131812487_Change_Again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
